### ISSUE TITLE
it's possible for an ALB with multiple target groups to have a target group with the wrong port

### ISSUE THREAD

**Issue by imsky** [coreos/alb-ingress-controller#148]
ran into this issue today:

* service is created with node port 30000, ingress with ports 80 and 443 is created
* ALB is created, with a port 80 listener routing requests to the port 30000 target group
* service is replaced while ingress is created (changing the node port to 30999)
* ALB is finalized, with a port 443 listener routing requests to the port 30999 target group

the controller does not seem to perform a check to verify that the listeners are 1) using the same target group 2) using the correct group after the ALB is created. this also leads to stale target groups in EC2.

**Comment by joshrosso** [comment]
@imsky I believe i worked through the same issue today in https://github.com/coreos/alb-ingress-controller/issues/207

We've done a lot of work with the listener and target group logic and it seems to be solved in version `b30d8d28`. 

If you're still using the controller, feel free to validate this. If your results return otherwise, please describe your observations and we'll try to tackle it as part of milestone 1.0 (https://github.com/coreos/alb-ingress-controller/pull/197)
