### ISSUE TITLE
controller does not respect alb.ingress.kubernetes.io/security-groups annotation

### ISSUE THREAD

**Issue by d-shi** [coreos/alb-ingress-controller#232]
I'm not sure if this was a recent intended change, but deploying the recent versions of the alb ingress controller gave me these 403 errors from AWS:

`UnauthorizedOperation: You are not authorized to perform this operation.`

Looking at CloudTrail, it was trying to call CreateSecurityGroup, which we do not give to our nodes. I tried giving it this access, and the controller proceeded to create 2 new security groups for each ALB and attach one to the ALB and one to our nodes. This is despite the fact that we explicitly provide the `alb.ingress.kubernetes.io/security-groups` annotation on our ingresses.

**Comment by joshrosso** [comment]
Hi @d-shi thanks for the report. I'm looking into this now.

**Comment by joshrosso** [comment]
@d-shi I've tackled this and included it in the version `1.0-alpha.3`.

Could you let me know if this works for you now?

**Comment by d-shi** [comment]
Hi @joshrosso,

Thanks for the quick reply and fix. I've tried out `1.0-alpha.3` and it is working as I expected now!

**Comment by Dmitriy1984Molchanov** [comment]
Hello, getting such an error but can't understand reasons

`kubectl describe -f ingress.yaml 
Name:             api
Namespace:        default
Address:          
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /*   ssl-redirect:use-annotation (<error: endpoints "ssl-redirect" not found>)
              /*   forward-single-tg:use-annotation (<error: endpoints "forward-single-tg" not found>)
              /*   api:8080 (192.168.10.28:8080,192.168.24.225:8080)
Annotations:  alb.ingress.kubernetes.io/actions.forward-single-tg:
                {"type":"forward","targetGroupARN": "arn:aws:elasticloadbalancing:us-west-2:145262151028:targetgroup/k8s-default-api-85d6f51d52/88adea9134...
              alb.ingress.kubernetes.io/actions.ssl-redirect:
                {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
              alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:145262151028:certificate/b448af9d-0e88-4090-b5a2-d095260a3f95
              alb.ingress.kubernetes.io/group.name: api-prod
              alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}, {"HTTPS":443}]
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: instance
              kubernetes.io/ingress.class: alb
Events:
  Type     Reason            Age   From     Message
  ----     ------            ----  ----     -------
  Warning  FailedBuildModel  33m   ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 071b0312-d0fe-4fbd-a183-78fdaf725cf9
  Warning  FailedBuildModel  33m  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 011545ec-ddae-445b-b89d-0a726edea025
  Warning  FailedBuildModel  33m  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 6672ff2a-bc9a-4460-9654-4d23f767c528
  Warning  FailedBuildModel  33m  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: f0a01b6d-85af-4449-b4c4-8336c995d8c6
  Warning  FailedBuildModel  33m  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: d820edc8-91ad-4a8f-9dda-a351a162d64e
  Warning  FailedBuildModel  33m  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: fd216fe2-4681-482f-a9c2-496b88f43530
  Warning  FailedBuildModel  33m  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: b60d1fff-d184-4449-87a2-ee5cdb752dd6
  Warning  FailedBuildModel  33m  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 3b71371a-76b4-480d-81e0-da7da2186a88
  Warning  FailedBuildModel  33m  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 98b13657-4b02-480b-8045-93e40f5d2694
  Warning  FailedBuildModel  22m (x9 over 33m)  ingress  (combined from similar events): Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: d511c61c-b7c4-4e38-b9a7-895e16264a95
  Warning  FailedBuildModel  11m  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 973e0d28-9dcf-4ab2-bfee-d4404131e594
  Warning  FailedBuildModel  3m13s  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: e2cb7788-3df4-41b8-84e9-2c9f4ada5249
  Warning  FailedBuildModel  3m12s  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 1dccf878-8e40-411e-9d7a-a1fba02575bc
  Warning  FailedBuildModel  3m12s  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: f34358c5-d95b-45f7-8cdb-606b4110b2ea
  Warning  FailedBuildModel  3m12s  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 89e08977-7821-499b-8bcb-86d1eb4c9c0b
  Warning  FailedBuildModel  3m11s  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: f10db1a7-cd0f-4956-b826-c6c52bd376ef
  Warning  FailedBuildModel  3m11s  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: b4709f52-70f3-42d6-b2ae-f6b2483cf792
  Warning  FailedBuildModel  3m11s  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 013a7d98-4540-4fff-8886-2d55c3894506
  Warning  FailedBuildModel  3m10s  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: a348446e-df4c-4ff5-9975-07b9909c7200
  Warning  FailedBuildModel  3m9s  ingress  Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: 045e4c7c-4f0b-413e-9331-ce02c325a464
  Warning  FailedBuildModel  6s (x16 over 3m8s)  ingress  (combined from similar events): Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: dc2640c1-f7c4-434b-9194-4fa0944df079
`
