### ISSUE TITLE
VPC Security Groups per instance limit exceeded

### ISSUE THREAD

**Issue by MrPink** [coreos/alb-ingress-controller#337]
When I run services it automatically creates the Node Security Group and assigns it to the node, the limit on VPC security nodes attached to an instance is 5. Is this a known limitation with the controller or can I specify an existing node security group, in the documentation it says

>  It will also create a security group for instances that allows all TCP traffic when the source is the security group created for the ALB.

Any help appreciated!

**Comment by MrPink** [comment]
This limit can be increased by contacting AWS support - closing ticket

**Comment by rexroof** [comment]
This should be reopened.   I've run into this problem and it would be very helpful if the alb-ingress-controller grouped security groups together so that more than one rule is in each group.
Also, in most cases, the groups are effectively all the same and are all accomplishing the same exact things, so they might as well just be one group with one basic rule.
