### ISSUE TITLE
[Feature] Annotation for read timeout

### ISSUE THREAD

**Issue by Awk34** [coreos/alb-ingress-controller#79]
I don't know Go, but I would like to help add an annotation for the load balancer's read idle timeout setting (defaults to 60s). How could I start on trying to get this implemented?

**Comment by bigkraig** [comment]
You'll want to add support for reading the annotation to https://github.com/coreos/alb-ingress-controller/blob/master/controller/config/annotations.go. `SuccessCodes` is probably a good one to replicate.

Adding support for configuring the ALB with this is going to be a little more complicated, since you will need to leverage `LoadBalancerAttribute`'s, which we are not yet using. The corresponding information will need to be saved in the `LoadBalancer` struct, compared in `.needsModification()`, and updated in the `.modify()` func.

**Comment by joshrosso** [comment]
This is almost completed.
