### ISSUE TITLE
How does it compare with kube-ingress-aws-controller?

### ISSUE THREAD

**Issue by hjacobs** [coreos/alb-ingress-controller#85]
How does this ALB controller compare with [kube-ingress-aws-controller](https://github.com/zalando-incubator/kube-ingress-aws-controller)? 

* How does it create Application Load Balancers? (as far as I understand it will create one ALB per Ingress resource, `kube-aws-ingress-controller` creates one ALB per SSL cert, i.e. reuses ALBs across Ingress resources)
* How does it select the right SSL certificate? (`kube-ingress-aws-controller` does autodiscovery of both AWS ACM and AWS IAM SSL certificates based on the hostname)
* How does it handle DNS records? (kube-ingress-aws-controller does not create Route53 records, but instead relies on [External DNS](https://github.com/kubernetes-incubator/external-dns) )
* Does it support routing based on hostname? (as far as I understand it does not support this because AWS ALB only recently added the feature, `kube-ingress-aws-controller` does the host/path routing in the HTTP Proxy)
* How does the stack compare to `kube-ingress-aws-controller`? (ALB + NodePort vs ALB + HTTP Proxy + Service)
* When should a user use this ALB controller and when is the `kube-ingress-aws-controller` the better choice?
* Who is running it in production and what are the experiences so far? (`kube-ingress-aws-controller` is running in production in Zalando in various clusters since January 2017)

The `kube-ingress-aws-controller` is also described on http://kubernetes-on-aws.readthedocs.io/en/latest/admin-guide/kubernetes-in-production.html#ingress

**Comment by bigkraig** [comment]
Hey @hjacobs, let me explain

* How does it create Application Load Balancers? (as far as I understand it will create one ALB per Ingress resource, `kube-aws-ingress-controller` creates one ALB per SSL cert, i.e. reuses ALBs across Ingress resources)
** This controller will at least one ALB per hostname per ingress resource. AWS released the host based routing just a couple of days before we were going to open source this and we thought it would be better to get it out as-is, rather than refactoring to support the AWS host based routing. The controller was written with Ticketmasters use cases in mind, and we preferred separating ALBs per ingress (for us, a service) rather than per cluster, to distribute our load more horizontally.
 
* How does it select the right SSL certificate? (`kube-ingress-aws-controller` does autodiscovery of both AWS ACM and AWS IAM SSL certificates based on the hostname)
** This controller requires the ARN of the certificate to use. If autodiscovery is something people end up preferring, it shouldn't be difficult to support.

* How does it handle DNS records? (kube-ingress-aws-controller does not create Route53 records, but instead relies on [External DNS](https://github.com/kubernetes-incubator/external-dns) )
** We use the hostname in the ingress resource and walk through the domain/subdomains to find the most specific Route53 zone. Records are the created/modified/deleted to support the hostname in the ingress resource. This works pretty well but there may be times when people want to specify the zone id, or use the External DNS controller. Having route53 built in was a good fit before the host based routing support and there is an open issue to leverage the External DNS controller already.
 
* Does it support routing based on hostname? (as far as I understand it does not support this because AWS ALB only recently added the feature, `kube-ingress-aws-controller` does the host/path routing in the HTTP Proxy)
** It's supported via the creation of an ALB per hostname. Now that the ALB supports this natively, we would like to move to a single ALB per ingress resource.
 
* How does the stack compare to `kube-ingress-aws-controller`? (ALB + NodePort vs ALB + HTTP Proxy + Service)
** This was the second major reason why we decided to write this. With `service.beta.kubernetes.io/external-traffic: OnlyLocal` annotation and this ingress controller, you get the least-hops path into your pod. All workers are added to the ALB TargetGroup but only the workers that have the pod running locally will pass the healthchecks. It removes a layer in the path and reduces latency. 

* When should a user use this ALB controller and when is the `kube-ingress-aws-controller` the better choice?
** In my opinion, if the routing rules of the ALB do everything you need and you do not need a HTTP Proxy or if you are concerned about running all of your clusters traffic through a single ALB, this controller is better suited.

* Who is running it in production and what are the experiences so far? (`kube-ingress-aws-controller` is running in production in Zalando in various clusters since January 2017)
** Ticketmaster has been using this controller in production since April 2017.

Thanks!

**Comment by hjacobs** [comment]
Another question: how does it handle autoscaling, i.e. ELB connection draining for scale down? (`kube-ingress-aws-controller` handles this by catching `SIGTERM` in the HTTP proxy / Skipper daemon set and therefore disabling the ALB health check "just in time" before terminating the node / EC2 instance).

**Comment by bigkraig** [comment]
The controller relies on the graceful shutdown of pods and the pod itself respecting the `SIGTERM` or configuring a `preStop` lifecycle hook.

**Comment by hjacobs** [comment]
@bigkraig thanks for the quick and elaborate answers! :smile:

**Comment by bigkraig** [comment]
🤘
