### ISSUE TITLE
Stop using master nodes

### ISSUE THREAD

**Issue by owenhaynes** [coreos/alb-ingress-controller#92]
Stop master nodes being added to the target group. Master nodes should not handle this traffic.

**Comment by joshrosso** [comment]
We'll be going forward with using the presence of the following label as an indicator that the node is a master node.

```
node-role.kubernetes.io/master
```

With this, we'll be taking the approach made in https://github.com/coreos/alb-ingress-controller/pull/94 (thanks @owenhaynes) but going forward with slightly different code due to how the ingress library has changed and this difference in the labeling mentioned above.
